### PR TITLE
Update create-component-page script

### PR DESCRIPTION
**Pull request by ethanWallace**
# Summary | Résumé

Update the `create-component-page` script to create pages that are closer to the final documentation pages. New pages will have all shortcodes and more complex sections, like the anatomy list, already on the page. The publisher will just need to fill in the relevant information after. Pages will appear under the coming-soon section until `state` has been updated.

## Usage

To use the `create-component-page` script, run `npm run create-component-page`. A prompt for `English name:` and `French name:` will appear, continue by entering the name of the component in both languages. After entering that information, English and French component pages will be created.

### Example

```
npm run create-component-page
English Name: File uploader
French name: Téléverseur de fichiers
```

This will generate the directories `/src/en/components/file-uploader/` and `/src/fr/composants/televerseur-de-fichiers/` with `base.md`, `use-case.md`, `design.md` and `code.md` files in them.

### CODE REVIEW

**Review by melaniebmn — APPROVED** [review]
Looks great - ship it! Thank you for updating the templates!

**Comment by melaniebmn** [comment]
Oops one more thought: Could we also automate adding the link for each new component to the link JSON file for each language?

**Comment by melaniebmn** [comment]
Oops one more thought: Could you add the description to our readme as well, please?

**Comment by ethanWallace** [comment]
> Oops one more thought: Could you add the description to our readme as well, please? It can be in a separate PR since the text will need to be translated.

Good idea, I will start writing the text this sprint so we can hopefully get it in the README quickly

**Pull request merged**
