### PR TITLE
docs: update CDN installation instructions

### PR DESCRIPTION
**Pull request by melaniebmn**
# Summary | Résumé

Update CDN installation instructions on the website. As a user, I want to use a specific version of the gcds packages so that my application does not get any breaking changes.

[Zenhub ticket](https://app.zenhub.com/workspaces/design-system-6100624a19f4cf000e46e458/issues/gh/cds-snc/design-gc-conception/753)

### CODE REVIEW

**Review by daine — APPROVED** [review]
LGTM! I wonder if we can change the title or commit message to `docs:` just before merge instead of refactor? TIA!

**Review by ethanWallace — APPROVED** [review]
LGTM

I also have a question. I know we talked about having the version number in the installation instructions update automatically without us needing to deploy the site again. With this approach the version only updates when a new deploy happens, is this intentional?

**Comment by daine** [comment]
@ethanWallace @melaniebmn good catch -- could we change it so that `getLatestCdnVersion` is not called in the eleventy build command, but rather from the installation instructions page?

**Comment by melaniebmn** [comment]
> @ethanWallace @melaniebmn good catch -- could we change it so that `getLatestCdnVersion` is not called in the eleventy build command, but rather from the installation instructions page?

I'm looking into it but we might be stuck with the current solution because of the code highlighter.

**Review by ethanWallace — APPROVED** [review]
LGTM!

**Pull request merged**
